### ISSUE TITLE
bootstrap.R function

### ISSUE THREAD

**Issue by voremargot** [UBC-MDS/strapR#11]

**Comment by BooleanJulien** [comment]
Hey @gauthampughazhendhi running into an issue with your function, where setting estimator = mean and then passing estimator to the substitute as character function returns "estimator" which triggers your error calls

Could you please find another way of testing that estimator is one of the supported functions?

Thanks!

![image](https://user-images.githubusercontent.com/20956707/151281846-3f2d5069-3a4f-4487-a440-fd41a26b3e0b.png)
