### ISSUE TITLE
Add your info to the Description File

### ISSUE THREAD

**Issue by BooleanJulien** [UBC-MDS/strapR#4]
Using the general file updates feature branch, please add your author information to the description file using the format provided.

```
person("First", "Last", , "first.last@example.com", role = c("aut", "cre"),
           comment = c(ORCID = "YOUR-ORCID-ID"))
```

I'm not certain how this works... maybe it's part of the individual assignment, so @voremargot if you've done that please advise if there is a better/correct way of doing this.

**Comment by voremargot** [comment]
@BooleanJulien  For this we want to create one of these for each author, replacing the first name, last name, and email. We keep the roles the same (author and creator) and remove the comment. Orcid is a database system that holds researchers information which you usually attach to journal publications (among other things). We don't need to worry about it for this project. Does that clarify things?
